#!/usr/bin/perl -i.bak
#usage:  mobfilt #.mob

$D = 0;

while (<>) {
    chop;

    if (/^\#\d+\s*/) {
        $D = 1;
    }

    if (/^(\w+) (\w+) (-?\d+) (\w)\s*/) {
        if ($D == 1) {
            print $1, " 0 0 0 ", $2, " 0 0 0 ", $3, " ", $4, "\n";
            $D = 0;
        } else {
            print "$_\n";
        }
    } else {
        print "$_\n";
    }
}